name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  dart_odbc:
    path: ../
  dotenv: ^4.2.0
  path: ^1.9.1


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
