name: dart_odbc
description: A Dart package for interacting with ODBC databases. It allows you to connect to ODBC data sources and execute SQL queries directly from your Dart applications.
version: 6.2.0
repository: https://github.com/SL-Pirate/dart_odbc

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  windows:
  linux:
  macos:

dependencies:
  ffi: ^2.1.2
  logging: ^1.3.0

dev_dependencies:
  dotenv: ^4.2.0
  ffigen: ^20.1.1
  lints: ^6.0.0
  open_url: ^2.0.1
  test: ^1.24.0
  very_good_analysis: ^10.0.0

topics:
  - db
  - database
  - odbc
  - sqlserver
  - oracle
