name: dart_odbc
description: A Dart package for interacting with ODBC databases. It allows you to connect to ODBC data sources and execute SQL queries directly from your Dart applications.
version: 3.1.2+2
repository: https://github.com/SL-Pirate/dart_odbc

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.1.2

dev_dependencies:
  ffigen: ^13.0.0
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0

topics:
  - db
  - database
  - odbc
  - sqlserver
  - oracle
